# Generated by Django 3.2 on 2023-05-14 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20230514_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Неверно введен код цвета. Надо использовать HEX коды', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
