# Generated by Django 3.2 on 2023-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='is_favorited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
