# Generated by Django 3.2.19 on 2023-05-23 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_auto_20230521_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, default=False, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
