# Generated by Django 3.2.19 on 2023-05-24 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20230523_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
