# Generated by Django 3.2.19 on 2023-05-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipes_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Recipe'},
        ),
    ]
