version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env
      

  web:
    image: paulsh1988/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate"

  frontend:
    image: paulsh1988/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
    - web
    - frontend


volumes:
  static_value:
  media_value:
  db_foodgram: