# Generated by Django 3.2.19 on 2023-05-21 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20230521_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='following',
            new_name='author',
        ),
    ]
